report/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'report'
urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),
#    path('dashboard_creator', views.dashboard_creator, name='dashboard_creator'),
    path('create', views.create, name='create'),
    path('documents', views.documents, name='documents'),
    path('erase/<page_slug>', views.erase, name='erase'),
    path('<page_slug>/input', views.input, name='input'),
    path('<page_slug>/submissions/<int:pk>', views.edit, name='edit'),
    path('<page_slug>/submissions', views.submissions, name='submissions'),
    path('<page_slug>/approval', views.approval, name='approval'),
    path('<page_slug>/delete', views.delete, name='delete'),
    path('<page_slug>/deletion/<int:pk>', views.deletion, name='deletion'),
    path('profile', views.profile, name='profile'),
    path('completed', views.completed, name='completed'),
]

shmaperalloy/report/urls.py
from django.urls import path

from . import views

app_name = 'report'
urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),
    path('input', views.input, name='input'),
#    path('edit/<int:taskname_id>', views.edit, name='edit'),
    path('edit', views.edit, name='edit'),
    path('submissions', views.submissions, name='submissions'),
    path('completed', views.completed, name='completed'),
]

shmaperalloy/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as accounts_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', accounts_views.register, name='register'),
    path('report/', include('report.urls')),
    path('profile/', accounts_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

report/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.template.defaultfilters import slugify
#from django.contrib.auth.models import User
from accounts.models import Member

class Docname(models.Model):
    doc_name = models.CharField(max_length=50)
    doc_text = models.TextField(max_length=250, blank=True)
#    doc_creator = models.CharField(max_length=40)
    doc_creator = models.ForeignKey(Member, on_delete=models.PROTECT)
    input_date = models.DateTimeField(default=timezone.now)
    page_slug = models.SlugField()
    owner = models.ManyToManyField(Member, blank=True, related_name='doc_owner')
    contributor = models.ManyToManyField(Member, blank=True, related_name='doc_contributor')

    def assign_contributor(current_document, selected_member):
        current_document.contributor.add(selected_member)

    def assign_owner(current_document, selected_member):
        current_document.owner.add(selected_member)

    def __str__(self):
        return self.doc_name

class Taskname(models.Model):
    docname = models.ForeignKey(Docname, on_delete=models.CASCADE, default=1)
    task_name = models.CharField(max_length=200)
    task_text = models.TextField('submission')
#    input_contributor = models.CharField(max_length=40)
    input_contributor = models.ForeignKey(Member, on_delete=models.PROTECT)
#    edit_contributor = models.CharField(max_length=40, default="None")
#    edit_contributor = models.ForeignKey(Member, null=True, on_delete=models.SET_NULL)
    hours_worked = models.DecimalField(max_digits=4, decimal_places=1)
    input_date = models.DateTimeField(default=timezone.now)
    edit_date = models.DateTimeField(default=timezone.now)

    # Represent status of comment. Could create custom Model Field.
    SUBMITTED = 0
    APPROVED = 1
    DISAPPROVED = 2
    STATUS_CHOICES = (
        (SUBMITTED, 'Submitted'),
        (APPROVED, 'Approved'),
        (DISAPPROVED, 'Disapproved'),
    )
    task_status = models.IntegerField(
        choices=STATUS_CHOICES,
        default=0,
    )

    def get_absolute_url(self):
        return reverse('submissions', kwargs={'id': self.id})

    def __str__(self):
        return self.task_name + '|' + self.task_text + '|' + self.input_contributor + '|' + str(self.hours_worked)

report/forms.py
from django import forms
from django.forms import models
from django.utils.translation import gettext_lazy as _
from .models import Taskname, Docname

#Form to create new content for a document
class SubmissionForm(forms.ModelForm):
    class Meta:
        model = Taskname
        fields = ["task_name", "input_contributor", "task_text", "hours_worked"]
        labels = {
            "task_name": _('Section'),
            "task_text": _('Content'),
        }

#Form to create new document
class DocForm(forms.ModelForm):
    class Meta:
        model = Docname
#        fields = ["doc_name", "doc_text", "doc_creator"]
        fields = ["doc_name", "doc_text"]

#customizing ModelChoiceField in Django to have more control over object data
class NewModelChoiceIterator(models.ModelChoiceIterator):
    def choice(self, obj):
        return (self.field.prepare_value(obj),self.field.label_from_instance(obj),obj)

class NewModelChoiceField(models.ModelMultipleChoiceField):
    def _get_choices(self):
        if hasattr(self, '_choices'):
            return self._choices
        return NewModelChoiceIterator(self)

    choices = property(_get_choices, forms.MultipleChoiceField._set_choices)

#create dataset of tasks with checkbox selected
class ApprovalForm(forms.ModelForm):
    tasks = forms.ModelMultipleChoiceField(
#        widget = forms.CheckboxSelectMultiple,
#    )

    #tasks = NewModelChoiceField(
        queryset = Taskname.objects.all(),
        widget = forms.CheckboxSelectMultiple,
    )

report/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
#from django.views.generic.edit import UpdateView, CreateView
from django.urls import reverse
from django.template.defaultfilters import slugify

from .models import Taskname, Docname
from .forms import SubmissionForm, DocForm, ApprovalForm

@login_required
def dashboard(request):
#    latest_task_list = Taskname.objects.all().order_by('-input_date')
    document_list = Docname.objects.order_by('-input_date')[:100]
    return render(request, 'report/dashboard.html', {'document_list': document_list})

#def dashboard_creator(request):
#    document_list = Docname.objects.order_by('-input_date')[:100]
#    return render(request, 'report/dashboard_creator.html', {'document_list': document_list})

def create(request):
    form = DocForm(request.POST)
    if request.method == 'POST':
        form = DocForm(request.POST)
        if form.is_valid():
            doc = form.save(commit=False)
            doc.doc_creator = request.user
            doc.page_slug = slugify(doc.doc_name)
            doc.save()
            doc.owner.add(request.user)
            doc.save()
            document_list = Docname.objects.order_by('-input_date')[:100]
            messages.success(request, ('Document has been created!'))
            return HttpResponseRedirect(reverse('report:documents'))
        else:
            form = DocForm()
            return render(request, 'report/create.html', {'form':form})
    return render(request, 'report/create.html', {'form':form})


def erase(request, page_slug):
    doc = get_object_or_404(Docname, page_slug=page_slug)
    doc.delete()
    document_list = Docname.objects.order_by('-input_date')[:100]
    messages.success(request, ('Document has been deleted.'))
    return HttpResponseRedirect(reverse('report:documents'))

def documents(request):
    document_list = Docname.objects.order_by('-input_date')[:100]
    return render(request, 'report/documents.html', {'document_list': document_list})

@login_required
def input(request, page_slug):
    doc = get_object_or_404(Docname, page_slug=page_slug)
    if request.method == 'POST':
        form = SubmissionForm(request.POST)
#check whether form is valid
        if form.is_valid():
            task = form.save(commit=False)
            task.docname = doc
            task.save()
            latest_task_list = Taskname.objects.all().order_by('-input_date')
            messages.success(request, ('Submission has been logged!'))
            return HttpResponseRedirect(reverse('report:submissions', args=(doc.page_slug,)))
#            return render(request, 'report/submissions.html', {'latest_task_list': latest_task_list})
#       Always return an HttpResponseRedirect after successfully dealing 
#       with post data.    
    else:
        form = SubmissionForm()
        return render(request, 'report/input.html', {'form': form,'page_slug': page_slug})

    return render(request, 'report/input.html', {'form': form, 'page_slug': page_slug})

def edit(request, pk, page_slug):
    doc = get_object_or_404(Docname, page_slug=page_slug)
    task = get_object_or_404(Taskname, pk=pk)
    if request.method == 'POST':
        form = SubmissionForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            latest_task_list = Taskname.objects.all().order_by('-input_date')
            messages.success(request, ('%s has been edited.' % task.task_name))
            return render(request, 'report/submissions.html', {'page_slug': page_slug, 'latest_task_list': latest_task_list})
    else:
        form = SubmissionForm(instance=task)
        return render(request, 'report/edit.html', {'form':form, 'page_slug': page_slug})
    return render(request, 'report/edit.html', {'form':form, 'page_slug': page_slug})   

def deletion(request, page_slug, pk):
    doc = get_object_or_404(Docname, page_slug=page_slug)
    task = get_object_or_404(Taskname, pk=pk)
    task.delete()
    latest_task_list = Taskname.objects.order_by('-input_date')[:100]
    messages.success(request, ('Submission has been deleted.'))
    return HttpResponseRedirect(reverse('report:submissions', args=(doc.page_slug,)))

def delete(request, page_slug):
    doc = get_object_or_404(Docname, page_slug=page_slug)
    latest_task_list = Taskname.objects.order_by('-input_date')[:100]
    if request.method == 'POST':
        if 'delete' in request.POST:
            for item in request.POST.get('tasks'):
                t = get_object_or_404(Taskname, pk=item)
                t.delete()
                messages.success(request, ('%s was deleted.' % t.task_name))
    return HttpResponseRedirect(reverse('report:submissions', args=(doc.page_slug,)))

def approval(request, page_slug):
    doc = get_object_or_404(Docname, page_slug=page_slug)
    
    if request.method == 'POST':
        tasks = request.POST.get('tasks')
#        for item in tasks:
        t = get_object_or_404(Taskname, pk=tasks)
        t.task_status = 1
        latest_task_list = Taskname.objects.order_by('-input_date')[:100]
        messages.success(request, ('%s is the object retrieved.' % t.task_name))
#        messages.success(request, ('%s was approved.' % tasks))
    return HttpResponseRedirect(reverse('report:submissions', args=(doc.page_slug,)))

def submissions(request, page_slug):
    doc = get_object_or_404(Docname, page_slug=page_slug)
    latest_task_list = Taskname.objects.filter(docname__page_slug=page_slug).order_by('-input_date')[:100]
#    t = get_object_or_404(Taskname, pk=1)
#    t2 = get_object_or_404(Taskname, pk=1)
#    if request.method == 'POST':
#        t = get_object_or_404(Taskname, pk=2)
#        for item in request.POST.get('tasks'):
#            t = get_object_or_404(Taskname, pk=item)
#            t.task_status = 1
#        form = ApprovalForm(request.POST)
#        if 'approve' in request.POST:
#                for item in form.POST.getlist('tasks'):
#            for item in form.cleaned_data['tasks']:
#                item.task_status = 1
#                t = get_object_or_404(Taskname, pk=item)
#                    t = latest_task_list.filter(pk=item)
#                    t.task_status = 1

    return render(request, 'report/submissions.html', {'page_slug': page_slug, 'doc': doc, 'latest_task_list': latest_task_list})

#def approval(request, page_slug):
#    doc = get_object_or_404(Docname, page_slug=page_slug)
#    latest_task_list = Taskname.objects.order_by('-input_date')[:100]
#    if request.method=='POST':
#        print(tasks)
#    return HttpResponseRedirect(request.GET.get('next'))
#    return HttpResponseRedirect(reverse('report:submissions', args=(doc.page_slug,)))
#    return render(request, 'report/submissions.html', {'page_slug': page_slug, 'doc': doc, 'latest_task_list': latest_task_list})

def profile(request):
    return render(request, 'report/profile.html')

def completed(request):
    return HttpResponse("The following report has been compiled")

shmaperalloy/report/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.views.generic.edit import UpdateView, CreateView
from django.urls import reverse

from .models import Taskname
from .forms import SubmissionForm

#class SubmissionCreate(CreateView):
#        model = Taskname
#        fields = ['task_name', 'task_text', 'input_contributor', 'hours_worked']

#class SubmissionUpdate(UpdateView):
#    model = Taskname
#    fields = ['task_name', 'task_text', 'input_contributor', 'hours_worked']
#    template_name_suffix = '_edit_form'
#    template_name_suffix = '_update_form'

def dashboard(request):
#    return HttpResponse("Welcome, Jimmy Bob")
    latest_task_list = Taskname.objects.order_by('-input_date')[:100]
    return render(request, 'report/dashboard.html', {'latest_task_list': latest_task_list})

def input(request):

    form = SubmissionForm()
#    return render(request, 'report/input.html', {'form': form})
    if request.method == 'POST':
        form = SubmissionForm(request.POST)
#check whether form is valid
        if form.is_valid():
            form.save()
            latest_task_list = Taskname.objects.order_by('-input_date')[:100]
#            messages.success(request, ('Submission has been logged!'))
#            return render(request, 'report/submissions.html', {'latest_task_list': latest_task_list})
            return HttpResponse("The form is valid.")
    
    else:
        form = SubmissionForm()
        latest_task_list = Taskname.objects.order_by('-input_date')[:100]
#        return render(request, 'report/input.html', {'latest_task_list': latest_task_list})
        return render(request, 'report/input.html', {'form': form})

    return render(request, 'report/input.html', {'form': form})

#def edit(request, taskname_id):
#    if request.method == 'POST':
#        task = Taskname.objects.get(pk=taskname_id)
#        form = SubmissionForm(task)
#        form = SubmissionUpdate(task)
#        if form.is_valid():
#            form.save()
#            latest_task_list = Taskname.objects.order_by('-input_date')[:100]
#    task.delete()
#            messages.success(request, ('Submission has been edited.'))
#            return redirect('submissions')
#    else:
#        task = Taskname.objects.get(pk=taskname_id)
#        form = SubmissionForm(task)
#        form = SubmissionUpdate(task)
#    return render(request, 'report/edit.html', {'form':form})   


def submissions(request):
    latest_task_list = Taskname.objects.order_by('-input_date')[:100]
    return render(request, 'report/submissions.html', {'latest_task_list': latest_task_list})

def completed(request):
    return HttpResponse("The following report has been compiled")

report/templates/report/base.html
{% load static from staticfiles %}
{% static "report/chewbaccaheadshot.jpeg" as profile_pic %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
     <!-- Import materialize.css -->
     <link type="text/css" rel="stylesheet" href="{% static 'report/materialize.css' %}"  media="screen,projection"/>
     <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

     <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" type="text/css" href="{% static 'report/base.css' %}">


</head>
<body>

<!--    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
-->
  <div class="navbar-fixed">
    <nav>
      <div class="nav-wrapper blue darken-4">
        {% if user.is_authenticated %}
        <a href="{% url 'report:dashboard' %}" class="brand-alt">ALT96IO</a>

        <ul id="nav-mobile" class="right hide-on-med-and-down blue-text text-lighten-5">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'report:create' %}">New Document</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'report:documents' %}">Documents</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profile' %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>  
        </ul>
        {% else %}
        <a href="#" class="brand-alt">ALT96IO</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down blue-text text-lighten-5">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'register' %}">Register</a>
          </li>
        </ul>
        {% endif %}
      </div>
    </nav>
  </div>


    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
            {% block content %}
            {% endblock %}


            <!--JavaScript at end of body for optimized loading-->
    <script type="text/javascript" src="report:materialize.js"></script>
    <script type="text/javascript" src="report:base.js"></script>


</body>

</html>

report/templates/report/base_old.html
{% load static from staticfiles %}
{% static "report/chewbaccaheadshot.jpeg" as profile_pic %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
<!--    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous"> -->
     <!-- Import materialize.css -->
     <link type="text/css" rel="stylesheet" href="{% static 'report/materialize.css' %}"  media="screen,projection"/>
     <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

     <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" type="text/css" href="{% static 'report/base.css' %}">


</head>
<body>

<!--    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
-->
  <div class="navbar-fixed">
    <nav>
      <div class="nav-wrapper blue darken-4">
        {% if user.is_authenticated %}
        <a href="{% url 'report:dashboard' %}" class="brand-alt">ALT96IO</a>

        <ul id="nav-mobile" class="right hide-on-med-and-down blue-text text-lighten-5">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'report:input' %}">New Entry</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'report:submissions' %}">Report</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profile' %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        </ul>
        {% else %}
        <a href="#" class="brand-alt">ALT96IO</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down blue-text text-lighten-5">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'register' %}">Register</a>
          </li>
        </ul>
        {% endif %}
      </div>
    </nav>
  </div>

  {% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
      {{ message }}
    </div>
  {% endfor %}
  {% endif %}

            {% block content %}
            {% endblock %}

            <!--JavaScript at end of body for optimized loading-->
    <script type="text/javascript" src="report/materialize.js"></script>
    <script type="text/javascript" src="report:base.js"></script>


</body>

</html>

report/templates/report/dashboard.html
{% extends "report/base.html" %}

{% block content %}
<h2><center>Welcome!</center></h2>


{% if document_list %}

    <div id="logged">
        <div class="grey lighten-3">
            <h4>Owner Report List</h4>
            <div style="padding: 0px 10px 10px 10px;">

    <table class="table table-bordered highlight white">
        <thead>
            <th>Report Name</th>
            <th>Owner</th>
            <th>Date Created</th>
            <th>Add</th>
            <th>Delete</th>
        </thead>
        <tbody>
        {% for lists in document_list %}
            {% if lists.doc_creator == user %}    
                <tr>
                
                    <td><a href="{% url 'report:submissions' lists.page_slug %}">{{ lists.doc_name }}</a></td>
                    <td>{{ lists.doc_creator }}</td>
                    <td>{{ lists.input_date }}</td>
                    <td><a href="{% url 'report:input' lists.page_slug %}"><center><i class="material-icons md-light hoverable">create</i></center></a></td>
                    <td><center><a href="{% url 'report:erase' lists.page_slug %}"><i class="material-icons md-light hoverable">clear</i></a></center></td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table> 
            </div>
        </div>
    </div>


        <div id="logged">
            <div class="grey lighten-3">
                <h4> Contributor Report List</h4>
                <div style="padding: 0px 10px 10px 10px;">

    <table class="table table-bordered highlight white">
        <thead>
            <th>Report Name</th>
            <th>Owner</th>
            <th>Date Created</th>
            <th>Add</th>
            <th>Delete</th>
        </thead>
        <tbody>
        {% for lists in document_list %}
            {% if lists.doc_creator != user %}    
                <tr>
                
                    <td><a href="{% url 'report:submissions' lists.page_slug %}">{{ lists.doc_name }}</a></td>
                    <td>{{ lists.doc_creator }}</td>
                    <td>{{ lists.input_date }}</td>
                    <td><a href="{% url 'report:input' lists.page_slug %}"><center><i class="material-icons md-light hoverable">create</i></center></a></td>
                    <td><center><a href="{% url 'report:erase' lists.page_slug %}"><i class="material-icons md-light hoverable">clear</i></a></center></td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table> 

            </div>
        </div>
    </div>

{% endif %}



{% endblock %} 

report/templates/report/dashboard_creator.html
{% extends "report/base.html" %}

{% block content %}
<h2><center>Welcome!</center></h2>

<div class="container">
    <div class="row">
        <div class="col s12">

<div class="container">
    <div id="logged">

{% if document_list %}
    <table class="table table-bordered highlight reponsive-table">
        <thead>
            <th>Document Title</th>
            <th>Owner</th>
            <th>Date Created</th>
        </thead>
        <tbody>
        {% for lists in document_list %}    
            <tr>
                
                <td><a href="{% url 'report:submissions' lists.page_slug %}">{{ lists.doc_name }}</a></td>
                <td>{{ lists.doc_creator }}</td>
                <td>{{ lists.input_date }}</td>
                <td><a href="{% url 'report:input' lists.page_slug %}"><center><i class="material-icons md-light hoverable">create</i></center></a></td>
                <td><center><a href="{% url 'report:erase' lists.page_slug %}"><i class="material-icons md-light hoverable">clear</i></a></center></td>
            </tr>
        {% endfor %}
        </tbody>
    </table> 

{% endif %}
    </div>
</div>

</div>
</div>
</div>


{% endblock %}

report/templates/report/dashboard_tasks.html
{% extends "report/base.html" %}

{% block content %}
<h2><center>Welcome!</center></h2>

<div class="container">
    <div class="row">
        <div class="col s12">

<div class="container">
    <div id="logged">

{% if latest_task_list %}
    <table class="table table-bordered highlight reponsive-table">
        <thead>
            <th>Title</th>
            <th>Description</th>
            <th>Contributor</th>
            <th>Hours</th>
        </thead>
        <tbody>
        {% for lists in latest_task_list %}    
            <tr>
                <td>{{ lists.task_name }}</td>
                <td>{{ lists.task_text }}</td>
                <td>{{ lists.input_contributor }}</td>
                <td><center>{{ lists.hours_worked }}</center></td>
                <td><a href="{% url 'report:edit' lists.pk %}"><center><i class="material-icons md-light hoverable">create</i></center></a></td>
                <td><center><a href="{% url 'report:deletion' lists.pk %}"><i class="material-icons md-light hoverable">clear</i></a></center></td>
            </tr>

        {% endfor %}
        </tbody>
    </table> 

{% endif %}
    </div>
</div>

</div>
</div>
</div>


{% endblock %}

report/templates/report/submissions.html
{% extends "report/base.html" %}

{% block content %}

<ul id="slideout-filter" class="sidenav">
    <li><a href="#">Submitted</a></li>
    <li><a href="#">Approved</a></li>
    <li><a href="#">Disapproved</a></li>
</ul>
<a href="#" data-target="slideout-filter" class="sidenav-trigger"><i class="material-icons">menu</i></a>

<div class="row">
    <div class="col s12 m6 l6">

    <div id="logged">
        <div class="grey lighten-3">
            <h4> {{ doc.doc_name }} </h4>
            <h6>Owner: {{ doc.doc_creator }}</h6>
            <div>
                <p>
                    {{ doc.doc_text }}
                </p>
            </div>
        </div>
        
                
{% if latest_task_list %}
    <form action="" name="TaskForm" method="POST">
            {% csrf_token %}
    <table class="table table-bordered highlight responsive-table">
        <thead>
            <th>Section</th>
            <th>Content</th>
            <th>Member</th>
            <th>Hours</th>
            <th>Date Created</th>
        </thead>
        <tbody id="content_table">
        {% for lists in latest_task_list %}   
            <tr>
                <td>
                    <label>
                        <input type="checkbox" value="{{lists.pk}}" name="tasks">
                        <span>{{ lists.task_name }}</span>
                    </label>
                </td>
                <td>{{ lists.task_text }}</td>
                <td>{{ lists.input_contributor }}</td>
                <td><center>{{ lists.hours_worked }}</center></td>
                <td>{{ lists.input_date|date:"F j, Y" }}</td>
                <td><a href="{% url 'report:edit' page_slug lists.pk %}"><center>Edit</center></a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <button class="waves-effect waves-light btn" type="submit" name="delete" formaction="{% url 'report:delete' page_slug %}">Delete</button>
    <a class="waves-effect waves-light btn" href="{% url 'report:input' page_slug %}">Add Task</a>
    </form>     
{% else %}
    <p>No submissions entered.</p>
{% endif %}
    </div>


</div>
</div>

<div class="row">
    <div class="col s12, m3, l3">
        <ul class="collapsible popout">
            <!--Discussion box -->
            <li>
                <div class="collapsible-header">Discussion</div>
                <div class="collapsible-body">
                    <p>Comment 1 <br> Comment 2</p>
                </div>
            </li>
        </ul>
    </div>
</div>

<!--
<script type=text/javascript>
function updateStatus(latest_task_list){
    document.getElementById("test").innerHTML = "You clicked the button";
    alert(latest_task_list);
    for (i=0; i<3;i++) {
        if (TaskForm.tasks[i].checked) {
            latest_task_list[i].task_status = 1;
        }
    }
}
</script>
-->

{% endblock %}